name: Upload HTML to DigitalOcean Spaces

on:
  push:
    branches:
      - main  # Trigger this action when pushing to the main branch

jobs:
  upload-to-digitalocean:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Upload Content to Digitalocean Spaces
      # You may pin to the exact commit or the version.
      # uses: kodertroop/do-space-sync-action@4dd3c681a654f55679ee68f23e536d66914a1b43
      uses: kodertroop/do-space-sync-action@v1.0.1
      with:
          # Source Dir form where files have to be uploaded
          SOURCE_DIR: ./public # default is ./public
          # Region of DO spaces
          SPACE_REGION: SFO3 # default is blr1
          # DO spaces SPACE_ACCESS_KEY_ID
          SPACE_ACCESS_KEY_ID: ${{ secrets.S3_KEY }} # default is 
          # DO spaces SPACE_SECRET_ACCESS_KEY
          SPACE_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET }} # default is 
