name: Upload HTML to DigitalOcean Spaces

on:
  push:
    branches:
      - main  # Trigger this action when pushing to the main branch

jobs:
  upload-to-digitalocean:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.S3_KEY }}
        aws-secret-access-key: ${{ secrets.S3_SECRET }}
        aws-region: sfo3  # Update this to your region (e.g., sfo3, sgp1)

    - name: Upload HTML file to DigitalOcean Space
      run: |
        aws s3 cp ./SEA_Paths.html s3://iron/public/SEA_Paths.html --endpoint-url https://sfo3.digitaloceanspaces.com
