name: Upload HTML to DigitalOcean Spaces

on:
  push:
    branches:
      - main  # Trigger this action when pushing to the main branch

jobs:
  upload-to-digitalocean:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set DigitalOcean Spaces credentials
      run: |
        echo "AWS_ACCESS_KEY_ID=${{ secrets.S3_KEY }}" >> $GITHUB_ENV
        echo "AWS_SECRET_ACCESS_KEY=${{ secrets.S3_SECRET }}" >> $GITHUB_ENV

    - name: Upload HTML file to DigitalOcean Space
      run: |
        aws s3 cp ./SEA_Paths.html s3://iron/public/SEA_Paths.html --endpoint-url https://sfo3.digitaloceanspaces.com
